Icon
ALPHAVIO/BlogSite pull request #115
Opened 2021-02-03 15:07 UTC by HarshitAditya27

## What is the change?
I have added a favicon for the website, code written in header.ejs (code:).The favicon is located in the images folder which is inside the public folder and I have set the value of const URL which is const URL = process.env.URL; (as instructed by you) and one more thing the favicon created is simple it's just the logo with the border of color combination white and pink. I hope you will like my favicon :). (This PR is the updated version of issue no #107 )

Related issue?

## Related issue?
issue: #105  

## How was it tested?
I have tested the website by using the hyper terminal and mongod server.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate. 
![Screenshot (574)_LI](https://user-images.githubusercontent.com/71604531/106765998-6eb1bb80-665f-11eb-9863-878f5bf0af0c.jpg)

2021-02-03 15:21 UTC, Pranav016 requested changes
Delete the favicon from the assets folder if you've already added it to the images folder in public dir

2021-02-03 15:21 UTC, Pranav016 commented on app.js
> +
Why were these extra lines added

2021-02-03 15:21 UTC, Pranav016 commented on app.js
> + const URL = process.env.URL;
what was the need of adding space before this

2021-02-03 15:21 UTC, Pranav016 commented on views/partials/header.ejs
> +
extra line added

2021-02-03 15:23 UTC, Pranav016 commented
There are two commits in this PR, both for adding a favicon. Please avoid unnecessary commits, commit history needs to be clean. (Follow Contribution Guidelines)

2021-02-03 15:52 UTC, HarshitAditya27 commented on app.js
> +
Sir, I was not knowing about that maybe by mistake I added those lines please forgive me.

2021-02-03 15:59 UTC, Pranav016 commented on app.js
> +
It's fine, just the work in 1 commit. Make a branch from master and then work on it or squash your commits and then force push it.

2021-02-03 16:05 UTC, HarshitAditya27 commented on app.js
> +
Sir I  have deleted the two extra lines and removed the favicon from the assets folder, Are there any more changes that I have to do?

2021-02-03 16:08 UTC, HarshitAditya27 commented on app.js
> + const URL = process.env.URL;
Sir the file which I have pushed does not contain two const URLs,I don't know why it is showing a two const URL over here?

2021-02-03 16:52 UTC, Pranav016 commented on app.js
> +
No

2021-02-03 16:53 UTC, Pranav016 commented on app.js
> + const URL = process.env.URL;
This called diff, its not two URLs

2021-02-03 17:41 UTC, HarshitAditya27 commented on app.js
> +
Excuse me, sir, I have deleted extra lines and favicon from the assets folder as you have requested, can you see my commits? 
I hope I have resolved your issue :)

2021-02-03 17:45 UTC, HarshitAditya27 commented on app.js
> + const URL = process.env.URL;
ooh ok

2021-02-04 04:19 UTC, Pranav016 commented
There are 4 commits just for adding the favicon, please squash commits or make a PR from a new branch. The commit messages are incorrect.
`Deleted Favicon from assets (as requested)`

2021-02-04 04:58 UTC, HarshitAditya27 commented
Sir, I have sent you a screenshot that contains the commit history of this PR, I have assigned numbers to each commit, sir can you tell me which commits I have to squash by giving me the number of commit that I have assigned so that it would be easy for me to which commit I have to squash.
![Screenshot (575)_LI](https://user-images.githubusercontent.com/71604531/106846788-8e82c700-66d3-11eb-87b8-36f491ba9a1b.jpg)

2021-02-04 05:03 UTC, Pranav016 commented
> Sir, I have sent you a screenshot that contains the commit history of this PR, I have assigned numbers to each commit, sir can you tell me which commits I have to squash by giving me the number of commit that I have assigned so that it would be easy for me to which commit I have to squash.
> ![Screenshot (575)_LI](https://user-images.githubusercontent.com/71604531/106846788-8e82c700-66d3-11eb-87b8-36f491ba9a1b.jpg)

Squash 2,3,4 into 1

2021-02-04 05:39 UTC, HarshitAditya27 commented
Ok sir I will be squashing 2,3, and 4.

2021-02-04 06:32 UTC, HarshitAditya27 commented
Sir, I have squashed commit 2,3, and 4, please let me know if any error exists. Sir, I hope you like my changes :)

2021-02-04 06:42 UTC, HarshitAditya27 commented
Sir, I will be creating a new PR because it is becoming very hectic to squash the commits.

2021-02-04 09:36 UTC, Pranav016 commented
> Sir, I will be creating a new PR because it is becoming very hectic to squash the commits.

Yup, that'll be easier 👍

2021-02-04 09:49 UTC, HarshitAditya27 commented
Sir, I have already created a new PR  name "Added favicon successfully #117 " with only 1 commit and no extra lines (I have checked each and every document (which I have used)).I hope you will like my work :) and hope this time its gets merged ! .

2021-02-04 10:29 UTC, closed without merging