Sticky navbar
ALPHAVIO/BlogSite pull request #170
Opened 2021-02-14 08:07 UTC by pankajkumarbij

## What is the change?
Navbar is sticky at the top.

## Related issue?
issue: #167 

## How was it tested?
Code tested In my local system.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
NA

2021-02-14 09:22 UTC, Pranav016 commented
Add a screen-recording of the changes you made in this PR.

2021-02-14 09:40 UTC, pankajkumarbij commented
> * Add a screen-recording of the changes you made in this PR.
> * What labels should I put on the issue? JWoC?

I can only send screenshots.
It works in both desktop and mobile view, now the navbar is sticky on the top of the page, Navbar not moving with scroll.

I am a participant of both JWOC and MWOC but if you can give marks for only one then give marks for JWOC.

Mobile view:-

![Screenshot of Daily Journal](https://user-images.githubusercontent.com/59636849/107873176-8fd3a100-6ed6-11eb-9e2b-732d65e23108.jpg)

Laptop view:-

![screencapture-localhost-3000-2021-02-14-15_04_36](https://user-images.githubusercontent.com/59636849/107873178-92ce9180-6ed6-11eb-9bda-8472f90d15c3.png)

2021-02-14 11:25 UTC, Pranav016 requested changes
Minor changes required, and if you can add a screen recording of desktop and mobile view then that would be great otherwise I'll have to test it. use `Win + G` to use inbuilt screen recorder of windows or download a free screen recorder.

2021-02-14 11:25 UTC, Pranav016 commented on public/css/styles.css
> +  padding-bottom: 10px;
Update these to 1vh or 0.7 vh so that they'll be perfectly padded even in mobile view. Hard coding in pixels can effect responsiveness. I know before they were in pixels only, but if you can make them in `vh` or `vw` or `rem` then that would be great.

2021-02-14 11:25 UTC, Pranav016 commented on public/css/styles.css
> +  font-size: 40px;
Make this 2 or 3 `rem`

2021-02-14 11:25 UTC, Pranav016 commented on views/partials/header.ejs
> +  <body class="darkmode--activated" style="margin-top: 90px;">
Also check if the dark mode aligns correctly in both desktop and mobile view. Use relative units like `vh vw` or `rem`.

2021-02-15 05:25 UTC, pankajkumarbij commented
Now check :


https://user-images.githubusercontent.com/59636849/107908530-4047b080-6f7c-11eb-9bd0-79ad6ea328a6.mp4

2021-02-15 12:04 UTC, merged

2021-02-16 01:04 UTC, Pranav016 commented
@all-contributors please add @pankajkumarbij for code