Fixes Space UI changes
ALPHAVIO/BlogSite pull request #189
Opened 2021-02-17 12:41 UTC by RutvikJ77

## What is the change?
Updated the spacing arrangements on the web page.

## Related issue?
issue: #159 

## How was it tested?
Updated directly through the Developer tools. Unfortunately, there has been an issue running the project locally showing connection refused to the DB.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![Screenshot 2021-02-17 at 6 09 56 PM](https://user-images.githubusercontent.com/45565999/108205678-68d1d500-714b-11eb-95e8-cb9a6b7ec7e8.png)
![Screenshot 2021-02-17 at 6 10 05 PM](https://user-images.githubusercontent.com/45565999/108205702-6e2f1f80-714b-11eb-9535-229c08a14f6f.png)

2021-02-17 12:42 UTC, RutvikJ77 commented
Sorry was not able to run the app locally which hindered the dev. process. 😓

2021-02-17 18:19 UTC, Pranav016 requested changes
* How did you make UI changes without even running the app, these changes look redundant. Show me what error you are facing to run the app, I'll help you 👍 
* There is a new pull request for making the website responsive, after that gets merged it would be even better to improve the UI then.
* In the screenshot you shared, the footer looks like it is stuck at the top. I don't get it..
* The commit messages are also wrong. What is meaning of `Chore:` ?
* Change base branch of the PR to develop, don't make the PR to master. Check contribution guidelines.

2021-02-17 18:19 UTC, Pranav016 commented on views/partials/footer.ejs
> +<footer class="text-center text-white container" style="background-color:#07527e;width:100%;bottom: 0; margin-top: auto;padding:10px;">
Don't hard code values, that affects responsiveness, using relative units of measurements like `vh` or `vw` or `rem`.

2021-02-17 18:19 UTC, Pranav016 commented on views/partials/footer.ejs
> +          <a href="#!" style="color:white;"><i class="fa fa-award" style="padding-right: 3px;"></i>Careers</a>
Use relative units of measurements.

2021-02-17 18:21 UTC, Pranav016 commented
I am closing this PR for now, reopen if required.

2021-02-17 18:21 UTC, closed without merging

2021-02-18 05:38 UTC, RutvikJ77 commented
- Okay! I will attach the error.
- Okay! I will try to improve the PR once the responsive one gets merged.
- They are both different screenshots, mistakenly I uploaded the footer one first and then the spacing one.
- I am using the udacity commit style guide. Chore means a task.
- My bad, I will make sure I check the merging branch as well. 
- I agree, I will use the responsive values.

2021-02-21 01:58 UTC, Pranav016 commented
> * Okay! I will try to improve the PR once the responsive one gets merged.

You can work on this now, Idk when the responsive one gets merged. Since I am clearing assignees on issues more than 4-5 days old so let me know if you're still working..