Added background
ALPHAVIO/BlogSite pull request #196
Opened 2021-02-19 07:56 UTC by Aayush-hub

## What is the change?
Added background image.

## Related issue?
issue: #109 

## How was it tested?
Locally by contributor

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![Capture](https://user-images.githubusercontent.com/65889104/108474882-fb8e8300-72b5-11eb-8035-21d8ed5ed14d.png)

2021-02-19 11:45 UTC, Pranav016 reviewed
Is the background responsive? Does it stay intact in mobile view ? Can you add a screen recording showing how background stays the same in different views. Asking this cause I feel adding image by itself without any media queries or other css might break in mobile view.

2021-02-19 11:45 UTC, Pranav016 commented on app.js
> +const URL = "mongodb://localhost:27017/blogDB";
turn this back to `process.env.URL`
`"mongodb://localhost:27017/blogDB"` will only be used to run the website on a server locally on your machine.

2021-02-19 12:30 UTC, Aayush-hub commented
@Pranav016 Done with the changes!

2021-02-21 02:25 UTC, Pranav016 requested changes
### Shows this issue when I run the code on my machine. 
![image](https://user-images.githubusercontent.com/54665036/108613657-fa766680-7419-11eb-8206-5f83601cd4d1.png)

### Mobile view
![image](https://user-images.githubusercontent.com/54665036/108613673-10842700-741a-11eb-9bd5-faf83eda42a1.png)

### tablet view
![image](https://user-images.githubusercontent.com/54665036/108613683-2d205f00-741a-11eb-8add-2537af863cbc.png)

2021-02-22 10:48 UTC, Aayush-hub commented
@Pranav016 Sir, this was issue with website responsiveness not with the background image, though I am done with the changes and solved errors. Please review my PR.

2021-02-22 17:36 UTC, Pranav016 commented
> @Pranav016 Sir, this was issue with website responsiveness not with the background image, though I am done with the changes and solved errors. Please review my PR.

Yes, I agree there was some issue with responsiveness. A PR for making the site responsive got merged just now, you can try again by pulling that code.

2021-02-22 17:38 UTC, Pranav016 reviewed
It is working perfectly in mobile and tablet view but is still giving issue in desktop view.
![image](https://user-images.githubusercontent.com/54665036/108746770-c35f9c80-7562-11eb-9e52-15fa5239a972.png)

Responsiveness is now fixed, a new PR for that got merged. You can try one more time now.

2021-02-23 07:15 UTC, Aayush-hub commented
@Pranav016 Done with the changes. Please review my PR:)

2021-02-23 17:57 UTC, Pranav016 reviewed
Works fine now 👍  I saw a lot of media queries being put in the header.ejs under style tag clutters the file a little bit but, it's fine. We can work with it. The PR is ready to merge but the commit message `solved errors` that is used 2 times is incorrect. Please make a new PR with correct commit messages (try to be more specific with commit messages) or squash the current commits.

2021-02-24 06:45 UTC, Aayush-hub commented
@Pranav016 Sure, making a new PR:)

2021-02-24 06:45 UTC, closed without merging