Update styles.css
ALPHAVIO/BlogSite pull request #241
Opened 2021-03-08 20:21 UTC by satcasm

## What is the change?
Made the margin better under the navbar.

## Related issue?
issue: #232 

## Screenshots or Video:
![image](https://user-images.githubusercontent.com/56315878/110376967-d6ea2780-8079-11eb-8382-d5e2c284ac51.png)

2021-03-09 05:53 UTC, satcasm commented
Hey @Pranav016 , can you tell me why is it  getting failed here ? I can't comprehend the error message.

2021-03-09 13:43 UTC, Pranav016 commented
> Hey @Pranav016 , can you tell me why is it getting failed here ? I can't comprehend the error message.

Don't worry about it..

2021-03-09 16:50 UTC, satcasm commented
Also resolved issue: #234

2021-03-10 02:52 UTC, Pranav016 requested changes
* Don't commit to master branch. Work on a new branch
* Make separate PRs for separate issues.
* Set base branch to develop when making the PR
* Read contribution guidelines

2021-03-10 02:52 UTC, Pranav016 commented on public/css/styles.css
> +  margin-top: 25px;
Use relative units of measurement (eg. rem, em ,vh, vw) to keep website responsive.

2021-03-10 02:53 UTC, Pranav016 commented
Closing PR, make a new one from new branch.
Reopen PR if required

2021-03-10 02:53 UTC, closed without merging