Added workflow for GSSOC label
ALPHAVIO/BlogSite pull request #247
Opened 2021-03-09 06:58 UTC by Abhijay007

## What is the change?
Added workflow for GSSOC label

## Related issue?
issue: #237

## How was it tested?
tested on my local repo

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

2021-03-09 15:10 UTC, Pranav016 requested changes
Does this action check if GSSOC is mentioned anywhere in the issue body ? It'll be great if you can refer the issue description again.

2021-03-09 15:10 UTC, Pranav016 commented on .github/workflows/autoLabel.yaml
> +          default-labels: '["GSSOC"]'
Make default label `GSSOC21`

2021-03-09 16:17 UTC, Abhijay007 commented
> Does this action check if GSSOC is mentioned anywhere in the issue body ? It'll be great if you can refer the issue description again.

@Pranav016 sir I test with and without both GSSOC mention in the issue text.

***With***
![with label](https://user-images.githubusercontent.com/64387054/110501729-7b26a980-8120-11eb-9545-243aef93821d.PNG)

***Without***
![without text](https://user-images.githubusercontent.com/64387054/110501910-add0a200-8120-11eb-9a9e-145fb1d46830.PNG)

Sir see I raised this issue 3 minutes before that issue but as I did not mention GSSOC anywhere in the text the workflow didn't get triggered.

2021-03-09 21:24 UTC, Pranav016 approved these changes

2021-03-10 12:43 UTC, Pranav016 reviewed
@Abhijay007 Can you do one small things really quickly ? These labels should be added to any issue and 'any PR' that has "GSSOC","GSSOC21","gssoc","Gssoc","GSSoC" in their body. So just please make this small change and edit the action to add labels on pull request as well.
Since came to know late that labels need to be added on PRs as well so telling you know..

2021-03-10 12:46 UTC, Abhijay007 commented
> @Abhijay007 Can you do one small things really quickly ? These labels should be added to any issue and any PR that has "GSSOC","GSSOC21","gssoc","Gssoc","GSSoC" in their body. So just please make this small change and edit the action to add labels on pull request as well.
> Since came to know late that labels need to be added on PRs as well so telling you know..

ok sir I will do that, No problem!!

2021-03-12 08:04 UTC, Pranav016 commented
> > @Abhijay007 Can you do one small things really quickly ? These labels should be added to any issue and any PR that has "GSSOC","GSSOC21","gssoc","Gssoc","GSSoC" in their body. So just please make this small change and edit the action to add labels on pull request as well.
> > Since came to know late that labels need to be added on PRs as well so telling you know..
> 
> ok sir I will do that, No problem!!

Any progress ? The requested changes aren't that difficult. You just have to add to the `on` clause in the file. Let me know if you need any help

2021-03-12 09:39 UTC, Abhijay007 commented
> > > @Abhijay007 Can you do one small things really quickly ? These labels should be added to any issue and any PR that has "GSSOC","GSSOC21","gssoc","Gssoc","GSSoC" in their body. So just please make this small change and edit the action to add labels on pull request as well.
> > > Since came to know late that labels need to be added on PRs as well so telling you know..
> > 
> > 
> > ok sir I will do that, No problem!!
> 
> Any progress ? The requested changes aren't that difficult. You just have to add to the `on` clause in the file. Let me know if you need any help

sir, I tried to add the workflow for pull request by changing the `on` clause but when I run that workflow on my local repo that then that workflow crashes for every PR with or without GGSOC text in the body. then I try to make a separate workflow that is only for PR not issue included on the `on` clause but that also didn't work. I tried this process with almost 10 PRs in my local repo but not any PR get successful passed the labeler workflow checks. sir, I think that I need to find a new `uses` clause in order to set workflow for PRs.


thinks I tried:

![pr-workflow1](https://user-images.githubusercontent.com/64387054/110921342-76423f80-8344-11eb-9968-88628d33ea24.PNG)

with a separate workflow:
![PR-workflow2](https://user-images.githubusercontent.com/64387054/110921416-8823e280-8344-11eb-8788-9fd7776c36f3.PNG)


@Pranav016 sir, can you please cross-check it once on any other repo by changing the `on` clause for PR.

2021-03-12 20:00 UTC, Pranav016 reviewed
> > Any progress ? The requested changes aren't that difficult. You just have to add to the `on` clause in the file. Let me know if you need any help
> 
> sir, I tried to add the workflow for pull request by changing the `on` clause but when I run that workflow on my local repo that then that workflow crashes for every PR with or without GGSOC text in the body. then I try to make a separate workflow that is only for PR not issue included on the `on` clause but that also didn't work. I tried this process with almost 10 PRs in my local repo but not any PR get successful passed the labeler workflow checks. sir, I think that I need to find a new `uses` clause in order to set workflow for PRs.
> 
> thinks I tried:
> 
> ![pr-workflow1](https://user-images.githubusercontent.com/64387054/110921342-76423f80-8344-11eb-9968-88628d33ea24.PNG)
> 
> with a separate workflow:
> ![PR-workflow2](https://user-images.githubusercontent.com/64387054/110921416-8823e280-8344-11eb-8788-9fd7776c36f3.PNG)
> 
> @Pranav016 sir, can you please cross-check it once on any other repo by changing the `on` clause for PR.

Yes surely, I'll check whenever I get time.
One thing, was it working before you added the `pull_request` part ? I mean was it working fine for adding labels to issues ?

I'd suggest two things
1. Do like this 
![image](https://user-images.githubusercontent.com/54665036/110992016-5db14400-839b-11eb-8be3-87a1d28fd107.png)

1. Try removing the single quotation marks like this
![image](https://user-images.githubusercontent.com/54665036/110992143-89342e80-839b-11eb-96d3-cdddbabfb485.png)

I hope this resolves the issue and works fine

2021-03-13 07:09 UTC, Abhijay007 commented
> Yes surely, I'll check whenever I get time.
> One thing, was it working before you added the `pull_request` part ? I mean was it working fine for adding labels to issues ?

Yes, sir, it is working fine for the issue labeling.

2021-03-13 07:10 UTC, Abhijay007 commented
> I'd suggest two things
> 
> 1. Do like this
>    ![image](https://user-images.githubusercontent.com/54665036/110992016-5db14400-839b-11eb-8be3-87a1d28fd107.png)
> 2. Try removing the single quotation marks like this
>    ![image](https://user-images.githubusercontent.com/54665036/110992143-89342e80-839b-11eb-96d3-cdddbabfb485.png)
> 
> I hope this resolves the issue and works fine

ok sir I will try this .

2021-03-13 07:52 UTC, Abhijay007 commented
> I'd suggest two things
> 
> 1. Do like this
>    ![image](https://user-images.githubusercontent.com/54665036/110992016-5db14400-839b-11eb-8be3-87a1d28fd107.png)
> 2. Try removing the single quotation marks like this
>    ![image](https://user-images.githubusercontent.com/54665036/110992143-89342e80-839b-11eb-96d3-cdddbabfb485.png)
> 
> I hope this resolves the issue and works fine

No sir it didn't work, I don't know why but it runs fine with issue labeling but not for PR. Sir, can you please try this once for PRs labeling on any local repo whenever you get the time?

2021-03-13 09:12 UTC, merged

2021-03-13 09:12 UTC, Pranav016 commented
I'll take care of the PR part

2021-03-13 09:17 UTC, Abhijay007 commented
> I'll take care of the PR part

ok sir !!

2021-03-13 09:27 UTC, Pranav016 commented
I was testing this action and it auto added all the level labels as well 
![image](https://user-images.githubusercontent.com/54665036/111025767-4bbbb980-840c-11eb-82ad-fe5a04d04cc0.png)

Can you raise and issue for this and work on this bug again ?

2021-03-13 09:51 UTC, Abhijay007 commented
> I was testing this action and it auto added all the level labels as well which is not required.
> ![image](https://user-images.githubusercontent.com/54665036/111025767-4bbbb980-840c-11eb-82ad-fe5a04d04cc0.png)
> 
> Can you raise and issue for this and work on this bug again ?

I don't know why label action for levels gets triggered 😅 as I didn't mention it anywhere in the workflow. 
when I tested it on some of my local repos nothing like that happened.  I think it happened due to other workflows that are defined under repo.
sir I will try to figure out why those workflows get triggered once I am done with changes I will open a PR for that. till then you can raise an issue for that if you want.