Added constraint for username password & email for signup
ALPHAVIO/BlogSite pull request #261
Opened 2021-03-10 07:34 UTC by abhinav5481

## What is the change?
Added constraints in email, password & username for signup in server-side code.

## Related issue?
issue: #163 

## How was it tested?
I have tested by entering the invalid username password & email on my local machine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

#### Username Check: `username should be between 6 to 12 characters`
Upon entering the invalid username  an error would be returned from the server-side which would appear as
![image](https://user-images.githubusercontent.com/60434542/110592484-58d47080-81a0-11eb-9cd1-a6777c72d4b4.png)

#### Email Check:
Similar to username, email would be checked against the email regex and the error message would be shown on the screen

#### Password Check:  ` password must contain a minimum of 8 letters, with at least a symbol, upper and lower case letters and a number`
![image](https://user-images.githubusercontent.com/60434542/110592892-de582080-81a0-11eb-8bb0-76bc1e31dc0e.png)

Please review my code & let me know if any further changes are required.
Add a screenshot or demo video if appropriate.

2021-03-10 08:02 UTC, shudhanshu03 commented
Good Work @abhinav5481 . 
/reviewed

2021-03-10 08:04 UTC, shudhanshu03 commented
/reviewed

2021-03-10 08:06 UTC, shudhanshu03 reviewed
Good Work.

2021-03-10 12:56 UTC, shudhanshu03 commented
/merge/

2021-03-10 12:58 UTC, shudhanshu03 commented
/gssoc/ 
/level2/

2021-03-10 13:00 UTC, shudhanshu03 commented
/level2/

2021-03-10 19:45 UTC, Pranav016 commented
> /merge/

not ready to merge, base branch is master, should be `develop` for any kind of code changes

2021-03-10 19:49 UTC, shudhanshu03 commented
> > /merge/
> 
> not ready to merge, base branch is master, should be `develop` for any kind of code changes

@abhinav5481 Base branch should be develop. I am adding a image hope that might help you to change .
![Gs_Develop_Branch](https://user-images.githubusercontent.com/62972853/110688669-d8e1f100-8207-11eb-8bc2-29d182ae7800.png)

2021-03-10 19:56 UTC, Pranav016 commented
> > > /merge/
> > 
> > 
> > not ready to merge, base branch is master, should be `develop` for any kind of code changes
> 
> @abhinav5481 Base branch should be develop. I am adding a image hope that might help you to change .
> ![Gs_Develop_Branch](https://user-images.githubusercontent.com/62972853/110688669-d8e1f100-8207-11eb-8bc2-29d182ae7800.png)

good work

2021-03-11 20:07 UTC, shudhanshu03 commented
/merge/

2021-03-12 19:49 UTC, Pranav016 requested changes

2021-03-12 19:49 UTC, Pranav016 commented on app.js
> +// process.env.URL;
Revert this back, localhost is only to run it on local machine

2021-03-14 05:53 UTC, Pranav016 commented
Closing for now, reopen if required.

2021-03-14 05:53 UTC, closed without merging

2021-03-14 06:03 UTC, abhinav5481 commented on app.js
> +// process.env.URL;
Okay.
I will do it and commit it back