Fixed comman url issue [issue #264]
ALPHAVIO/BlogSite pull request #287
Opened 2021-03-11 15:23 UTC by prajjwalarora

## What is the change?
Replaced all Post title parameters with Post Id in endpoints and controller, as post title can be common that is creating ambiguity and causing this issue.

## Related issue?
issue: #264 

## How was it tested?
All the controllers after changes tested on the local system performing related operations.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
none

2021-03-11 17:13 UTC, RushanKhan1 commented
Hey! Thanks for contributing!
There's a typo in your commit message can you please fix that, meanwhile I'll review you pr.

2021-03-11 17:24 UTC, RushanKhan1 commented
I reviewed the pr and everything works fine, you have squashed the bug, great work!
So please fix the small typo and then I'll add the ``ready-to-merge`` tag.

2021-03-11 17:48 UTC, prajjwalarora commented
@RushanKhan1 I've fixed the typo in the commit message.

2021-03-12 09:37 UTC, prajjwalarora commented
@Pranav016 I've fixed the common URL issue in the new structured code. please review.

2021-03-12 19:47 UTC, Pranav016 requested changes
Few changes required.
Code looks fine, Add a screen recording that the site works perfectly when we interact with any post. 
Then we'll merge

2021-03-12 19:47 UTC, Pranav016 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +>>>>>>> adc8be918b298942fea3a2ce16d6be1c504062b9
These need to be removed

2021-03-12 19:47 UTC, Pranav016 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +>>>>>>> adc8be918b298942fea3a2ce16d6be1c504062b9
All the ones in this document or any other file that were added due to conflicts have to be removed

2021-03-12 21:29 UTC, prajjwalarora commented
@Pranav016 I've removed the text that came from conflicts.
here is the link to the video of the working website locally - [link to drive](https://drive.google.com/file/d/1u7WglOTt9aAFsvW-cWtnPap2v8q_UhmF/view?usp=sharing)

2021-03-13 17:05 UTC, merged