Mongo Error Warning Issue Solved
ALPHAVIO/BlogSite pull request #309
Opened 2021-03-12 10:41 UTC by srk224

## What is the change?
Mongoose Warning is now removed

## Related issue?
issue: #300 

## How was it tested?
![2021-03-12](https://user-images.githubusercontent.com/63584405/110928909-667b2900-834d-11eb-9023-0d422d9c7767.png)

2021-03-12 10:45 UTC, srk224 commented
can anyone let me know why 
some checks are not successful?

2021-03-12 13:48 UTC, AnanyaNegi commented
@srk224 you need to change the base branch from `ALPHAVIO: master` to `ALPHAVIO: develop`.
![Screenshot_20210126-095421__01__01](https://user-images.githubusercontent.com/54092197/110948703-af3fdb80-8367-11eb-82e7-ea3c15c4ebf4.png)

2021-03-12 13:49 UTC, AnanyaNegi commented
/gssoc/

2021-03-12 13:50 UTC, AnanyaNegi commented
/level2/

2021-03-12 13:52 UTC, Abhinaba006 commented
@srk224  sent pr to the develop branch, not in the main.

2021-03-13 05:19 UTC, srk224 commented
I have changed the branch from master to develop..can you please take a look?

2021-03-13 12:35 UTC, Pranav016 requested changes

2021-03-13 12:35 UTC, Pranav016 commented on app.js
> +const URL = "mongodb://localhost:27017/blogDB";
Revert this change

2021-03-13 12:35 UTC, Pranav016 commented on package.json
> +    "mongoose": "^5.11.15",
What is the need for this change ?

2021-03-13 12:35 UTC, Pranav016 commented
> can anyone let me know why
> some checks are not successful?

The checks are not tests right now, these are just workflows so don't worry

2021-03-13 13:08 UTC, srk224 commented on package.json
> +    "mongoose": "^5.11.15",
It was necessary to remove the depreciating warning

2021-03-13 13:10 UTC, srk224 commented
I have made the changes as you said. Please look into it and merge if everything is correct

2021-03-13 20:12 UTC, Pranav016 commented on package.json
> +    "mongoose": "^5.11.15",
We actually don't accept package upgrades from Pull requests, our bot does that for us plus there could be compatibility issues so that is why. Should I accept it from you ?

2021-03-13 20:13 UTC, merged