Change the color pallet of navbar
ALPHAVIO/BlogSite pull request #314
Opened 2021-03-12 18:57 UTC by hrushikesh-git

## What is the change?
Improve the Color pallet of the navbar used the shades of Green from the following colour palette
![color palate](https://user-images.githubusercontent.com/65762074/110985435-779a5900-8392-11eb-975b-6d532de80253.png)

And Changed the name from "Daily Journal" => "Quotidian Blogs" Quotadian is a synonym of Daily and bit of attractive.
![navbar change](https://user-images.githubusercontent.com/65762074/110985736-cfd15b00-8392-11eb-9317-ed6ae6b0cb6d.png)

2021-03-12 19:29 UTC, Pranav016 requested changes
* I think if the color of the whole navbar changes then that would be cool.. 
* Also I think a better color palate can be chosen, I like the color you chose for this, just a little brighter would do.
* Change base branch to develop
* I think the headline isn't very catchy/ attracting. `Quotidian BLOG'S`
I think a smaller word and either both words capitalized or only first letter looks subtle. Like `DAILY JOURNAL` or `Daily Journal`
* Resolve merge conflicts

2021-03-12 19:29 UTC, Pranav016 commented on app.js
> +mongoose.connect(URL, {useNewUrlParser: true, useUnifiedTopology: true,useCreateIndex:true});
Revert back this change, local host is only for running the project on your local machine

2021-03-12 19:30 UTC, Pranav016 commented
/reviewed

2021-03-13 12:25 UTC, Pranav016 commented
/gssoc/

2021-03-14 10:19 UTC, hrushikesh-git commented
@Pranav016  please review and merge the PR

2021-03-14 19:15 UTC, Pranav016 requested changes

2021-03-14 19:15 UTC, Pranav016 commented on views/partials/header.ejs
> +        <a class="navbar-brand" href="/"> <span class="navbar-brand-bold">Daily BLOG'S</span></a>
* I want a new name, `Daily BLOG'S` doesn't seem good. Also I want the title to be either all caps or only first letter capital as I had requested earlier (you might've missed)
* Can you add a demo img of the new color used for the navbar

2021-03-14 20:49 UTC, hrushikesh-git commented
![navbar change](https://user-images.githubusercontent.com/65762074/111083703-ce3f9880-8534-11eb-8e02-7bc1fd5389e0.png)

2021-03-15 21:55 UTC, Pranav016 commented
> * I think if the color of the whole navbar changes then that would be cool..
> * Also I think a better color palate can be chosen, I like the color you chose for this, just a little brighter would do.
> * Change base branch to develop
> * I think the headline isn't very catchy/ attractive `Quotidian BLOG'S`
>   I think a smaller word and either both words capitalized or only first letter looks subtle. Like `DAILY JOURNAL` or `Daily Journal`
> * Resolve merge conflicts

* Change base branch to develop as mentioned here. Take help from this on how to change 
![image](https://user-images.githubusercontent.com/54665036/111226396-116a3c00-8607-11eb-89fe-c37a5b03af79.png)
* Name it `ALPHAVIO BLOGS`.
Otherwise looks good to merge.

2021-03-16 07:34 UTC, hrushikesh-git commented
How to change base branch to develop ?

2021-03-16 08:10 UTC, RushanKhan1 commented
> > * I think if the color of the whole navbar changes then that would be cool..
> > * Also I think a better color palate can be chosen, I like the color you chose for this, just a little brighter would do.
> > * Change base branch to develop
> > * I think the headline isn't very catchy/ attractive `Quotidian BLOG'S`
> >   I think a smaller word and either both words capitalized or only first letter looks subtle. Like `DAILY JOURNAL` or `Daily Journal`
> > * Resolve merge conflicts
> 
> * Change base branch to develop as mentioned here. Take help from this on how to change
>   ![image](https://user-images.githubusercontent.com/54665036/111226396-116a3c00-8607-11eb-89fe-c37a5b03af79.png)
> * Name it `ALPHAVIO BLOGS`.
>   Otherwise looks good to merge.

@hrushikesh-git You can refer to the image attached above. You need to click on the button and then select ``develop``.

2021-03-16 14:36 UTC, hrushikesh-git commented
Sir I have made the things correct please look into it and guide me

2021-03-17 06:52 UTC, AnanyaNegi commented
> 
> 
> Sir I have made the things correct please look into it and guide me

Hi @hrushikesh-git .Can you attach the new screenshot of the navbar so I can have a look at the color?

2021-03-17 07:15 UTC, hrushikesh-git commented
![navbar change](https://user-images.githubusercontent.com/65762074/111429016-5cc33e00-871e-11eb-87a8-59f66569409f.png)
The color e same as above but the title is Changed according to the instruction to  ALPHAVIO BLOGS. The title is changed

2021-03-17 07:57 UTC, hrushikesh-git commented
> ![navbar change](https://user-images.githubusercontent.com/65762074/111429016-5cc33e00-871e-11eb-87a8-59f66569409f.png)
> The color is same as above but the title is Changed according to the instruction to ALPHAVIO BLOGS. The title is changed

everytime I solve one conflict a new conflict arise and I this time conflict is inside the CSS where I have changed the navbar colors I am not understanding what to do now

2021-03-17 08:00 UTC, Pranav016 commented
> > ![navbar change](https://user-images.githubusercontent.com/65762074/111429016-5cc33e00-871e-11eb-87a8-59f66569409f.png)
> > The color is same as above but the title is Changed according to the instruction to ALPHAVIO BLOGS. The title is changed
> 
> everytime I solve one conflict a new conflict arise and I this time conflict is inside the CSS where I have changed the navbar colors I am not understanding what to do now

Don't worry I'll fix it.

2021-03-18 05:28 UTC, RushanKhan1 commented
Hey @hrushikesh-git! Thanks for contributing! Actually, there have been some major changes to the code base to fix the bug that was in production also, there are still some more changes that need to be done therefore please **pull the updated code tomorrow** and make a new pr according to that else there will be a lot of merge conflicts.

2021-03-18 05:28 UTC, closed without merging