create license
ALPHAVIO/BlogSite pull request #34
Opened 2021-01-21 15:55 UTC by Swapna804

Resolved  #16

2021-01-21 17:56 UTC, Pranav016 commented
Is this PR solving 2 issues?

2021-01-21 17:58 UTC, Pranav016 commented
Always follow one best practice, if you're resolving two issues, make separate branches for them and don't commit anything to the master.

2021-01-22 10:56 UTC, Swapna804 commented
Actually i am new to open source, will keep in mind, thankyou.

2021-01-22 11:40 UTC, Pranav016 requested changes
Please make a new pull request with requested changes and from a new branch. Make separate PRs for separate issues.

2021-01-22 11:40 UTC, Pranav016 commented on LICENSE
> +Copyright (c) 2021 BlogSite
You never write project name in copyright, always write org name.
In this case write 
`Pranav016 and ALPHAVIO`

2021-01-22 11:40 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/faq
I requested some changes in these lines in #29 . Same mistakes were made. Please refer to it and correct them.

2021-01-22 11:40 UTC, closed without merging