Positioning of social icons Bug Fixes
ALPHAVIO/BlogSite pull request #397
Opened 2021-03-21 11:21 UTC by abhishek96k

## What is the change?
The position of social media icons  Bug fixes

## Related issue?
close: #391 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![issue-391 (1)](https://user-images.githubusercontent.com/54280252/111902809-30ccf300-8a65-11eb-91a2-6b80264d0eff.png)

2021-03-21 11:50 UTC, abhishek96k commented
Hey @Pranav016 
please help me how i can solve this error
![error](https://user-images.githubusercontent.com/54280252/111903696-8c997b00-8a69-11eb-8e0c-c2e711287b5b.png)

2021-03-21 14:49 UTC, Pranav016 commented
> Hey @Pranav016
> please help me how i can solve this error
> ![error](https://user-images.githubusercontent.com/54280252/111903696-8c997b00-8a69-11eb-8e0c-c2e711287b5b.png)

don't worry about this, this isn't a code check.

2021-03-21 14:52 UTC, Pranav016 requested changes
change base branch of the PR to develop

2021-03-21 14:52 UTC, Pranav016 commented on views/partials/footer.ejs
> +      <ul class="list-unstyled list-inline d-flex" style="margin-top:2%; margin-left: 20px;">
Instead of `px`  use a relative unit such as `vh or vw or rem` because `px` can affect the responsiveness of the website..

Also, can you try to add the css to its class in styles in css instead of inline css, that way code is cleaner. Otherwise no worries..

2021-03-21 14:52 UTC, Pranav016 commented
/reviewed

2021-03-22 09:16 UTC, Pranav016 requested changes
Change base branch to develop.
Also add a demo video demonstrating your changes in normal and mobile view.

2021-03-22 09:16 UTC, Pranav016 commented on public/css/styles.css
> +  margin-left: 20px;
Use relative units of measurement such as `vh rem or vw or em` instead of px to ensure responsiveness of the website is not affected.

2021-03-22 09:16 UTC, Pranav016 commented on views/partials/footer.ejs
> +  left: '18px', // default: 'unset'
Same change required here and wherever px was used as a unit.

2021-03-22 12:41 UTC, closed without merging