Removed short content from blog cards
ALPHAVIO/BlogSite pull request #467
Opened 2021-03-26 07:40 UTC by A7abhilash

## What is the change?
removed the short content visible on blog cards in home(/), category(/category), dashboard(/dashboard) and author(/author/:authorId) UI.
Correspondingly added posts partial as we are displaying the posts(blogcards) in same way in the above mentioned routes.

## Related issue?
close: #447 
Old pr: #462 

## How was it tested?
Tested the functioning and responsiveness thoroughly in localhost.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![2021-03-26](https://user-images.githubusercontent.com/66360717/112560382-185c3000-8df9-11eb-804c-59c3c03bd1cd.png)

2021-03-26 07:59 UTC, Pranav016 requested changes

2021-03-26 07:59 UTC, Pranav016 commented on views/partials/posts.ejs
> +            <% } %>
can we add a sneak peek of the post content like this
```
<div class="post-content-font">
    <%- post.blogContent.substring(0,1000) + ("...") %>
</div>
```

2021-03-26 08:41 UTC, A7abhilash commented on views/partials/posts.ejs
> +            <% } %>
If you say so then i can add... 
Should i make a separate or for that or make a new one?

2021-03-26 12:45 UTC, A7abhilash commented on views/partials/posts.ejs
> +            <% } %>
Umm.. I think lets move on with current feature... We can discuss adding the sneak peak in discord and come to a conclusion...

2021-03-26 18:56 UTC, Pranav016 commented on views/partials/posts.ejs
> +            <% } %>
I think sneak peek in the post was already there before this PR, I mean we can still discuss if you want to..

2021-03-26 23:37 UTC, A7abhilash commented on views/partials/posts.ejs
> +            <% } %>
This PR is for removing that sneak peek(short content) from the cards..

2021-03-27 10:44 UTC, Pranav016 commented on views/partials/posts.ejs
> +            <% } %>
I wanted to have the sneak peek, but I think you have raised a new issue to add that ?
So think I should merge this one..

2021-03-27 10:45 UTC, Pranav016 commented
@A7abhilash resolve conflicts carefully, I think it is ready to merge

2021-03-27 10:48 UTC, A7abhilash commented
> @A7abhilash resolve conflicts carefully, I think it is ready to merge

Yeah yeah🙌
I dont think there are conflicts... The master branch has the div of displaying posts but i had now kept it in partials right(you can also check this once)... So i think u can go on to merge

2021-03-27 11:06 UTC, Pranav016 commented
> > @A7abhilash resolve conflicts carefully, I think it is ready to merge
> 
> Yeah yeah🙌
> I dont think there are conflicts... The master branch has the div of displaying posts but i had now kept it in partials right(you can also check this once)... So i think u can go on to merge

I know it's just a partial added for the post but the merge button doesn't appear untill you resolve them..

2021-03-27 11:13 UTC, A7abhilash commented
> > > @A7abhilash resolve conflicts carefully, I think it is ready to merge
> > 
> > 
> > Yeah yeah🙌
> > I dont think there are conflicts... The master branch has the div of displaying posts but i had now kept it in partials right(you can also check this once)... So i think u can go on to merge
> 
> I know it's just a partial added for the post but the merge button doesn't appear untill you resolve them..

Umm... Then shall i make a new pr by resolving the conflict and then later in next pr ill add the partials on home ui also?

2021-03-27 11:17 UTC, Pranav016 commented
> > > > @A7abhilash resolve conflicts carefully, I think it is ready to merge
> > > 
> > > 
> > > Yeah yeah🙌
> > > I dont think there are conflicts... The master branch has the div of displaying posts but i had now kept it in partials right(you can also check this once)... So i think u can go on to merge
> > 
> > 
> > I know it's just a partial added for the post but the merge button doesn't appear untill you resolve them..
> 
> Umm... Then shall i make a new pr by resolving the conflict and then later in next pr ill add the partials on home ui also?

No, resolving doesn't require to make a new PR. Just click on `resolve conflicts` button and you can resolve them on github

2021-03-27 11:18 UTC, Pranav016 commented
resolved them

2021-03-27 11:18 UTC, Pranav016 approved these changes

2021-03-27 11:19 UTC, Pranav016 commented
/gssoc/

2021-03-27 11:19 UTC, Pranav016 commented
/level2/

2021-03-27 11:19 UTC, merged