Third Party Authentication[issue - #269]
ALPHAVIO/BlogSite pull request #472
Opened 2021-03-26 11:22 UTC by krishna-y2000

## What is the change?
Added one click google authentication to this website.

## Related issue?
close: #269 

## How was it tested?
Locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![image](https://user-images.githubusercontent.com/60214457/112624267-66058680-8e53-11eb-8c2a-3d737c1d7a97.png)
![image](https://user-images.githubusercontent.com/60214457/112624296-74ec3900-8e53-11eb-9635-92ecefb39346.png)

2021-03-26 11:37 UTC, krishna-y2000 commented
@Pranav016  ,
After a lot of hardship this is done in my system. So, as i send the message on discord the new changes of code are not running in everyone's  system . But my changes will not affect the new changes most probably.

I can give my google oauth credentials for fast review . Let me know if needed. 

Point to take care : 
As the user uses google authentication he does not have a username but has a fullName,email etc property . So , when he clicks the such button where url has property of userName then  error will occur .
Eg : Fake url :  ```localhost:3000/posts/userName ``` or something like this.
Solution :
1) Change all url to firstName property instead of userName .
2) After authentication by google first ask user to set the username . Now url with userName will work perfectly.  
Please review this pr and merge it . 
Thanks

2021-03-26 18:49 UTC, Pranav016 requested changes
* remove extra commented code
* based on your comment, I feel that this is just a half solution and could give errors. Cannot merge this now unless a complete PR is made.
* commit messages need to be improved thus can't merge

2021-03-27 06:05 UTC, krishna-y2000 commented
@Pranav016  ok , but do i need to make a newbranch for this and start from beginning ?  Is there any way so i need not to write the whole code again ? If yes , then please send the git command .
Here , i have made a newbranch and pulled the code from previous branch so , it don't need to write whole code but with the code all the commit messages also arrived that were in previous branch .  Please reply fast.

2021-03-27 06:46 UTC, Pranav016 commented
> @Pranav016 ok , but do i need to make a newbranch for this and start from beginning ? Is there any way so i need not to write the whole code again ? If yes , then please send the git command .
> Here , i have made a newbranch and pulled the code from previous branch so , it don't need to write whole code but with the code all the commit messages also arrived that were in previous branch . Please reply fast.

I'd suggest you squash the commits and then add a new cammit message when you squash. Squashing will combine the number of commits you decide into one and will allow you to add a new message for that. Also when you make your next PR, thoroughly test the code, I hope no bug arises due to change of params.

2021-03-27 06:46 UTC, Pranav016 commented
I noticed you were talking about changing url to first-name instead of username, but first-name can be same, username is unique..

2021-03-27 07:06 UTC, krishna-y2000 commented
> > @Pranav016 ok , but do i need to make a newbranch for this and start from beginning ? Is there any way so i need not to write the whole code again ? If yes , then please send the git command .
> > Here , i have made a newbranch and pulled the code from previous branch so , it don't need to write whole code but with the code all the commit messages also arrived that were in previous branch . Please reply fast.
> 
> I'd suggest you squash the commits and then add a new cammit message when you squash. Squashing will combine the number of commits you decide into one and will allow you to add a new message for that. Also when you make your next PR, thoroughly test the code, I hope no bug arises due to change of params.

Thanks , i will try this . I hope it will work.

2021-03-27 07:17 UTC, krishna-y2000 commented
> I noticed you were talking about changing url to first-name instead of username, but first-name can be same, username is unique..

@Pranav016  Yes , you are true . Here , my point was  that  when a new user comes by signing google oauth and if he goes to any url that contains userName property , he will get error because google oauth does not give userName property , so dont't make such urls Or firstly ask the user to set his userName.
Properties by google : 
 provider         
   id
   name
   displayName
   birthday
   relationship
   isPerson
   isPlusUser
   placesLived
   language
   emails
   gender
   picture
   coverPhoto

2021-03-27 08:27 UTC, krishna-y2000 commented
@Pranav016  hii , 
1) I have squash the commits and made these two new commit . i hope 2 commit will not make problem .
2) Removed all the unnecessary commented code in files.

As , i said earlier the new code is not working in everyone 's system . you need to test my branch if code is working in your local system. i am confident it will work as i am working from few days and also shared the screenshort above.

i am giving this temporary credential for google oauth for reviewing my work . Put it in .env file.
 SECRET_KEY = AlphaVio
URL = mongodb://localhost:27017/blogDB
GOOGLE_CLIENT_ID = 952135025410-v6itiqn5ot3b6ggfcqksncl0v1lf7u3d.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET = Y2ZCZbcu83vf4lbielo9H77j
CALLBACK_URL = http://localhost:3000/auth/google/callback

2021-03-28 10:44 UTC, Pranav016 commented
> > I noticed you were talking about changing url to first-name instead of username, but first-name can be same, username is unique..
> 
> @Pranav016 Yes , you are true . Here , my point was that when a new user comes by signing google oauth and if he goes to any url that contains userName property , he will get error because google oauth does not give userName property , so dont't make such urls Or firstly ask the user to set his userName.
> Properties by google :
> provider
> id
> name
> displayName
> birthday
> relationship
> isPerson
> isPlusUser
> placesLived
> language
> emails
> gender
> picture
> coverPhoto
> [Source](https://www.npmjs.com/package/passport-google-oauth2)

how about using id then, using first name isn't a good practice..

2021-03-28 10:49 UTC, Pranav016 requested changes

2021-03-28 10:49 UTC, Pranav016 commented on models/User.model.js
> -    required: true,
why were required = true removed ?

2021-03-28 10:49 UTC, Pranav016 commented on routes/user.router.js
> +  res.send('<h1>Log in Failed :(</h1>')
use return statements and try catch throughout the code

2021-03-28 10:49 UTC, Pranav016 commented on views/partials/header.ejs
> +                  </li>
Can you add a screenshot of this button, I don't thing it should be added as a `li`

2021-03-28 12:00 UTC, krishna-y2000 commented on models/User.model.js
> -    required: true,
It is because when user authenticate through google auth , it goes through schema and fill all the values that google contains in it and that matches through schema i.e email , firstname here.
User can only fullfill the above properties i.e my last message about google oauth property , otherwise it would throw error if i set them to ```required = true``` i.e case of userName 

It is just like GFG site where you can login by google but then you need to fullfill your details other required details manually .

2021-03-28 12:01 UTC, krishna-y2000 commented on routes/user.router.js
> +  res.send('<h1>Log in Failed :(</h1>')
Ok ,  I will do this .

2021-03-28 12:06 UTC, Pranav016 commented on models/User.model.js
> -    required: true,
But I don't think this is the correct way, your feature shouldn't hamper rest of the website features. Now anybody would be able to login without username etc and it would cause inconsistencies in the db.

2021-03-28 12:16 UTC, krishna-y2000 commented on views/partials/header.ejs
> +                  </li>
It is just a normal button which will call the api . Looks like ```log-in``` and ```log-out``` button .

I would suggest to just once clone this branch i.e  ```269-issuenew```  and check it locally . you already have the credentials of google.

2021-03-28 12:25 UTC, krishna-y2000 commented on models/User.model.js
> -    required: true,
> But I don't think this is the correct way, your feature shouldn't hamper rest of the website features. Now anybody would be able to login without username etc and it would cause inconsistencies in the db.

Exactly , that's the reason why issued is raised to login by email and password by doing so  it would sync with google oath. That's why i am saying again and again don't make no userName url  or else ask the user to first fill every details in schema if he/she wants to continue with site.

2021-03-29 20:12 UTC, krishna-y2000 commented
@Pranav016  I am closing this pr , as i have made a new one

2021-03-29 20:12 UTC, closed without merging