Alignment of buttons
ALPHAVIO/BlogSite pull request #477
Opened 2021-03-26 16:26 UTC by satcasm

Issue Reference: #407 
Before:
![image](https://user-images.githubusercontent.com/56315878/112518237-3442e000-8dbf-11eb-8926-7bf0f8ab2f3a.png)
After:
![image](https://user-images.githubusercontent.com/56315878/112518371-52104500-8dbf-11eb-8ecb-c4ef570b0f94.png)

2021-03-26 18:22 UTC, Pranav016 requested changes
change base branch to master

2021-03-26 18:27 UTC, satcasm commented
@Pranav016 done!

2021-03-27 22:04 UTC, Pranav016 approved these changes

2021-03-27 22:04 UTC, Pranav016 commented
/gssoc/

2021-03-27 22:04 UTC, Pranav016 commented
/level2/

2021-03-27 22:05 UTC, merged