user edit page is added
ALPHAVIO/BlogSite pull request #484
Opened 2021-03-27 17:37 UTC by Abhinaba006

## What is the change?
A new page is added to let the user edit their details after sign up.

## Related issue?
close: #427 

## How was it tested?
locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
when some when is logged in this option will be visible 
![image](https://user-images.githubusercontent.com/54203624/112729200-93d6f200-8f5d-11eb-9571-1af70f34442f.png)

the user option redirect them to a new page where they can edit their details and need to provide password to confirm changes.
![image](https://user-images.githubusercontent.com/54203624/112729228-bb2dbf00-8f5d-11eb-9c20-ba4b5ec1fcdf.png)

2021-03-27 22:03 UTC, Pranav016 requested changes
Changes look good, change base branch to master

2021-03-27 22:03 UTC, Pranav016 commented on package.json
> +    "dev": "nodemon app.js -e js,ejs"
was this added because changes in ejs files don't trigger nodemon to restart server ?

2021-03-28 03:33 UTC, Abhinaba006 commented on package.json
> +    "dev": "nodemon app.js -e js,ejs"
Yes, it will trigger to restart the server if an ejs file is changed

2021-03-28 03:38 UTC, Abhinaba006 commented
Sir kindly add the gssoc21 and level3 label to this pr as the issue have them 😅

2021-03-28 03:40 UTC, Abhinaba006 commented
I have changed the base to master

2021-03-28 10:41 UTC, Pranav016 commented
Changes look good, I think ready to merge, one question. There was a dashboard option in navbar when user is logged in. In your screenshot its not there..
Shouldn't edit profile function be there in user dashboard..
You can add a button for edit profile in user dashboard itself.

2021-03-28 13:22 UTC, Abhinaba006 commented
> Changes look good, I think ready to merge, one question. There was a dashboard option in navbar when user is logged in. In your screenshot its not there..
> Shouldn't edit profile function be there in user dashboard..
> You can add a button for edit profile in user dashboard itself.

I have done it before the dashboard was added, and after that I pulled the master, both are working fine together. Do I need to change them ?

2021-03-28 13:47 UTC, Pranav016 commented
> > Changes look good, I think ready to merge, one question. There was a dashboard option in navbar when user is logged in. In your screenshot its not there..
> > Shouldn't edit profile function be there in user dashboard..
> > You can add a button for edit profile in user dashboard itself.
> 
> I have done it before the dashboard was added, and after that I pulled the master, both are working fine together. Do I need to change them ?

You can raise a new issue and work on it or you can work in the same one..

2021-03-28 14:23 UTC, merged

2021-03-28 14:24 UTC, Pranav016 commented
/level2/

2021-03-28 14:24 UTC, Pranav016 commented
/gssoc/

2021-03-28 14:24 UTC, Pranav016 commented
> Changes look good, I think ready to merge, one question. There was a dashboard option in navbar when user is logged in. In your screenshot its not there..
> Shouldn't edit profile function be there in user dashboard..
> You can add a button for edit profile in user dashboard itself.

@Abhinaba006 you can do this in a new PR

2021-03-28 17:57 UTC, Abhinaba006 commented
@Pranav016 sir, in the issue it was labeled as level3 😅 I have no problem though, should I raise a issue to merge this user  edit option to the dashboard?

2021-03-29 04:50 UTC, Abhinaba006 commented
/assign