Third Party Authentication
ALPHAVIO/BlogSite pull request #514
Opened 2021-03-29 20:04 UTC by krishna-y2000

## What is the change?
Added one click google authentication to this website.

## Related issue?
close: #269 

## How was it tested?
locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
Before login 
![image](https://user-images.githubusercontent.com/60214457/112893121-df250800-90f7-11eb-814d-9ba8de227ba9.png)
After login
![image](https://user-images.githubusercontent.com/60214457/112893165-ee0bba80-90f7-11eb-9a52-411429921652.png)

2021-03-29 20:10 UTC, krishna-y2000 commented
@Pranav016  ,
I have made all the required changes . There are few files where i have made changes and again reverted to previous state so it showing change there also .

So, here the case is where there is userName property it will just show the user icon who is doing login by google oauth. when user will enter his userName by updating the profile he can see his username.
Eg : Here after user icon userName will come 
![image](https://user-images.githubusercontent.com/60214457/112893851-d123b700-90f8-11eb-9037-85a0b95050aa.png)
 
I would strongly suggest to run on your local system.

2021-03-30 14:10 UTC, Pranav016 requested changes

2021-03-30 14:10 UTC, Pranav016 commented on middlewares/auth.js
> +      console.log(user);
remove extra console logs and format the code using prettier since a lot of extra lines added

2021-03-30 14:10 UTC, Pranav016 commented on middlewares/auth.js
> -        name: user.userName,
this doesn't need to be removed

2021-03-30 14:10 UTC, Pranav016 commented on models/User.model.js
> -    required: true,
`required: true` cannot be removed

2021-03-30 14:10 UTC, Pranav016 commented on views/partials/posts.ejs
> +                    <%= post.userName %>
why was this change required ?

2021-03-30 14:10 UTC, Pranav016 commented on views/partials/header.ejs
> +                  </li>
don't add it to the header, if in the future we need to add more 3rd party auths. we cannot add all in the navbar.

Add the button on the sign up page

2021-03-30 14:10 UTC, Pranav016 commented on views/author.ejs
> +                <h4>AUTHOR: <%= user.userName %> <%= user.lastName %></h4>
how can you do username and lastname..

2021-03-30 14:12 UTC, Pranav016 commented
@AnanyaNegi @RushanKhan1 If you guys get time, please test the PR once especially the routes/ pages where changes were made.
Otherwise if I am free I'll test it.
I know all have exams so you can do it whenever you have a few minutes to spare 👍

2021-03-30 18:11 UTC, krishna-y2000 commented on middlewares/auth.js
> -        name: user.userName,
If you want me to not remove this , then i need to assign the google id to userName , then if user wishes to change it then he can do his own changes in  future .
Reason : Because google oauth does not provide userName property.
I hope this would be fine . Let me know what you want to do ?

2021-03-30 18:13 UTC, krishna-y2000 commented on views/partials/posts.ejs
> +                    <%= post.userName %>
Due to this code only my project was not working earlier . It is giving same result as before even after removing this particular code-word.

2021-03-30 18:13 UTC, krishna-y2000 commented on views/partials/header.ejs
> +                  </li>
Ok, I  have applied this.

2021-03-30 18:14 UTC, krishna-y2000 commented on views/author.ejs
> +                <h4>AUTHOR: <%= user.userName %> <%= user.lastName %></h4>
It was a test check  , I forgot to remove . Apologise!!!

2021-03-30 18:19 UTC, krishna-y2000 commented
@Pranav016  , Let me know what you want me to do with userName ?
https://github.com/ALPHAVIO/BlogSite/pull/514#discussion_r604325653

2021-03-30 22:01 UTC, Pranav016 commented
How about we redirect the user who signs up using google auth to a page where he can add his missing fields like username etc before he can start using the application.
Or you can do something the other way around if someone clicks on the button, the person gets redirected where he adds his username etc and then gets authorized by google.


Also put your passport.js file middlewares folder

2021-03-30 22:04 UTC, Pranav016 commented on views/partials/posts.ejs
> +                    <%= post.userName %>
I checked on my system yesterday, it was working completely fine. Idk how it is giving error in your system

2021-03-31 08:23 UTC, krishna-y2000 commented on views/partials/posts.ejs
> +                    <%= post.userName %>
Actually , i searched a bit and found that this might have came due to version of mongoDB . Like , the latest mongoDB version is 3.x and mine 2.x .

2021-03-31 08:33 UTC, krishna-y2000 commented
@Pranav016  , Will it not be annoying for user ? I will redirect him to user profile page where he will fill all the details , ok ? Or should i make a new page where he will fill only his userName and then he will redirect to home page  ? 

yesterday i saw that when user authenticate by google than in profile property his firstName is the one google's  name  . So, the last name field is remained empty. It will be good if there is only property like ```fullName``` or just ```firstName``` . 

I will shift the file.

2021-04-02 13:54 UTC, Pranav016 commented
> @Pranav016 , Will it not be annoying for user ? I can redirect him to user profile page where he will fill all the other details .
> 
> yesterday i saw that when user authenticate by google than in profile property his firstName is the one google's name . So, the last name field will remain empty. It will be good if there is only property like `fullName` or just `firstName` .
> 
> I will shift the file.

Exactly what I said above..

2021-04-02 13:55 UTC, Pranav016 commented
@RushanKhan1 @AnanyaNegi can guide you get this PR merged, I am currently working on some other feature and too many dms in discord. Might not be able to give too much time here..

2021-04-05 23:29 UTC, Pranav016 commented
closing for now, reopen if required.

2021-04-05 23:29 UTC, closed without merging