Number of views in blogs added
ALPHAVIO/BlogSite pull request #520
Opened 2021-03-30 16:26 UTC by Rimpi246

## What is the change?
Added number of views in each blog

## Related issue?
issue_number#413 is also solved
close: #issue_number

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

2021-03-31 22:29 UTC, Pranav016 requested changes
* resolve conflicts, I'd suggest pull the new changes
* change default tab space in vs code from 2 to 4
* add a demo video or screenshot in PR description

2021-03-31 22:29 UTC, Pranav016 commented on package.json
>  }
redundant changes, not required.
restore to previous file

2021-04-01 20:15 UTC, Pranav016 commented
can you resolve conflicts and add a demo video of your feature ? I can merge it then..

2021-04-02 03:08 UTC, Rimpi246 commented
> can you resolve conflicts and add a demo video of your feature ? I can merge it then..

Yes sir, I am working on it

2021-04-05 23:38 UTC, Pranav016 commented
closing for now, reopen if required

2021-04-05 23:38 UTC, closed without merging