logo added
ALPHAVIO/BlogSite pull request #544
Opened 2021-04-01 07:34 UTC by aanchalrakheja

## What is the change?
added the logo in the navbar

## Related issue?
close: #386 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![image](https://user-images.githubusercontent.com/68388581/113259361-aa2cd700-92ea-11eb-9a52-91939567cd23.png)
![image](https://user-images.githubusercontent.com/68388581/113259420-bb75e380-92ea-11eb-96ce-9b7ff5c93d40.png)

2021-04-01 20:14 UTC, Pranav016 requested changes

2021-04-01 20:14 UTC, Pranav016 commented on public/css/styles.css
> +  margin-right:2rem;
reduce margin right, 2rem in mobile view is very big that is why the navbar brand comes in the center.
Hint- use `vw` unit here instead of `rem`

2021-04-01 20:14 UTC, Pranav016 commented on views/partials/header.ejs
>          <div class="container">
one more way, you can give this div a class and then apply some css to fix alignment

2021-04-01 20:14 UTC, Pranav016 commented on public/css/styles.css
> +  margin-right:2rem;
This would work most probably, otherwise the changes look good 👍

2021-04-01 20:50 UTC, aanchalrakheja commented
This is how it looks after the changes requested. Changed the unit to vw.
![image](https://user-images.githubusercontent.com/68388581/113352411-d895cb00-9359-11eb-9bad-2e8ffad9564a.png)

2021-04-01 20:54 UTC, Pranav016 commented
> This is how it looks after the changes requested. Changed the unit to vw.
> ![image](https://user-images.githubusercontent.com/68388581/113352411-d895cb00-9359-11eb-9bad-2e8ffad9564a.png)

How much is this, 2vw ? Try increasing the value a little and whatever feels suitable to you, you can commit that 👍

2021-04-02 04:30 UTC, Pranav016 commented
You can commit your code now, I'll merge

2021-04-02 09:21 UTC, aanchalrakheja commented
ok will commit the changes

2021-04-02 11:20 UTC, closed without merging