Implemented follow and unfollow feature
ALPHAVIO/BlogSite pull request #559
Opened 2021-04-02 12:12 UTC by tend2infinity

## What is the change?
1. I have made some changes in the User schema by adding followers and following arrays.
2. I have made two separate routes for following and unfollowing a user. 
3. I have also updated the dashboard.ejs and author.ejs by displaying the no of followers, following, and also the follow or unfollow button depending upon, if the logged-in user has followed the other person or not.
4. I have formatted files according to the prettier configuration.

## Related issue?
close: #534

## How was it tested?
It was tested on my local network

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/61948033/113414476-b2fcd600-93da-11eb-9a32-7769ddd46b8f.mp4

2021-04-03 09:00 UTC, Pranav016 requested changes
Changes look good. A couple queries-
* will I be able to see my follower or following list ? (if not, this feature should be there)
* can we follow without refreshing the page (ajax request ?) just a suggestion, optional to implement
* resolve merge conflicts

2021-04-03 09:29 UTC, tend2infinity commented
@Pranav016 
1. Regarding the followers and following list I can create a new page in the views folder and show the followers and following list in that (i.e. I can make a separate route /show-followers and /show-following and render information in that). Actually I was thinking of making a "MyFollowing" tab in the navbar so that I can show my followings as well as the blogs posted by people I follow.
2. I don't know about an AJAX request but I can surely read about that, but it may take a while
3. I will resolve the conflicts after implementing my point 1.

2021-04-05 23:19 UTC, Pranav016 approved these changes

2021-04-05 23:21 UTC, tend2infinity commented
I have successfully implemented the followers and following list on the dashboard.

2021-04-05 23:21 UTC, merged