moved inline styles from ejs files to styles.css issue#553
ALPHAVIO/BlogSite pull request #574
Opened 2021-04-03 17:40 UTC by Ayush0730

## What is the change?
I have removed all css from ejs files and replaced some of them with bootstrap classes, and others with different classes defined in styles.css

## Related issue?
close: #553 

## How was it tested?
After replacing some classes with bootstrap classes, I have checked the visual appearance and it looks same to me (very minor difference in margin etc.)

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

2021-04-03 21:57 UTC, Pranav016 requested changes
PR looks good, just a few changes

2021-04-03 21:57 UTC, Pranav016 commented on views/404.ejs
> +    <a href='https://www.freepik.com/vectors/website' class="d-none">Website vector created by stories - www.freepik.com</a>
I didn't notice this tag earlier, thanks for bringing it into notice.
 you can remove this tag and remove its corresponding css

2021-04-03 21:57 UTC, Pranav016 commented on public/css/styles.css
> +
rename these class names, could look confusing for a new contributors when he opens the ejs file and notices these classes

2021-04-03 21:57 UTC, Pranav016 commented on public/css/styles.css
> +.facebook {
add comments throughout the css file that helps distinguishing which section's css begins where..

2021-04-03 21:58 UTC, Pranav016 commented
/gssoc/

2021-04-03 21:58 UTC, Pranav016 commented
/level3/

2021-04-04 04:24 UTC, Ayush0730 commented on public/css/styles.css
> +
Okay. What about fsize and fweight? Are these names OK?

2021-04-05 08:53 UTC, Ayush0730 commented
@Pranav016 I have done the requested changes. Please check if it is okay

2021-04-05 23:28 UTC, Pranav016 approved these changes
Class names could be better but looks fine for now..

2021-04-05 23:28 UTC, Pranav016 commented
/gssoc/

2021-04-05 23:28 UTC, Pranav016 commented
/level3/

2021-04-05 23:28 UTC, merged