Added the search button hover style
ALPHAVIO/BlogSite pull request #585
Opened 2021-04-04 11:16 UTC by Shivam-Shandilya1

## What is the change?
Modified the search button style css by adding color to the hovering state.

## Related issue?
close: #576 

## How was it tested?
I have tested by running the localhost:3000 and inspecting through the google developer tool in my device.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/72553479/113506919-35b19c80-9565-11eb-8da0-87ca25d86958.mp4

2021-04-04 11:17 UTC, Shivam-Shandilya1 commented
Please review my pull request.

2021-04-04 19:33 UTC, Pranav016 requested changes

2021-04-04 19:33 UTC, Pranav016 commented on public/css/styles.css
> +}
I think this same style exists for all the other buttons on home page, can you reuse that code? Make a single class for adding that style and add that to all the buttons..
I think that's the whole idea of using a class.
I know its an addition to the issue but I feel cleaner code would be easier to debug 👍

2021-04-05 01:25 UTC, Shivam-Shandilya1 commented on public/css/styles.css
> +}
Okay

2021-04-07 14:11 UTC, Pranav016 commented
comment again to reopen PR..

2021-04-07 14:11 UTC, closed without merging