Email Verification Method
ALPHAVIO/BlogSite pull request #601
Opened 2021-04-05 18:40 UTC by osamamagdy

## What is the change?
1 - Adding string Status(to check whether he is Activated or not) and confirmation code in the user schema 
2 - Modified the signup function as when a new user is saved successfully in the database, he'll be marked as `Pending` instead of  direct login
3 - Then he will receive a confirmation email with a link that contains a unique encrypted confirmation code using nodemailer and jwt.
4 - The link will send a get request to the specific route with the confirmation code and if the user is already present in the database with that code, his account will be activated
5 - Then we redirect the user to the login page with a message that his account is finally activated.

NOTE : 
The Email and password of the send service must be written in the .env file like this 
`EMAIL = emailaddress@gmail.com`
`PASS = 123456789`

## Related issue?
close: #432 

## How was it tested?
I tried many test cases where the user can enter different emails and they all received different unique confirmation emails.

## Checklist:
- [X] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [X] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [X] Your submission doesn't break any existing feature.
- [X] Have you tested the code before submission?

2021-04-05 23:16 UTC, Pranav016 requested changes
Changes look good to merge, code is formatted 👍 
One small query that I asked.

Also next time make PR from a new branch, that's the best practice. Never commit to master.

2021-04-05 23:16 UTC, Pranav016 commented on models/Blog.model.js
> -module.exports = mongoose.model('Blog', blogSchema);
why was this moved up ?

2021-04-07 11:11 UTC, osamamagdy commented on models/Blog.model.js
> -module.exports = mongoose.model('Blog', blogSchema);
I think it was giving me a merge conflict because reformatting but it didn't had any effect

2021-04-07 11:35 UTC, closed without merging

2021-04-07 11:39 UTC, osamamagdy commented
I think I accidentally closed this PR
Can you reopen it @Pranav016 @AnanyaNegi @RushanKhan1

2021-04-07 11:40 UTC, osamamagdy commented
I also made some changes in a new branch but I didn't understand what happened all of a sudden

2021-04-07 12:48 UTC, Pranav016 commented
Not getting option to reopen PR, I think the branch was deleted..

2021-04-07 20:56 UTC, osamamagdy commented
I created another PR at #631 with the same changes. please review @Pranav016 @AnanyaNegi @RushanKhan1