Added user profile edit button on dashboard
ALPHAVIO/BlogSite pull request #666
Opened 2021-04-09 17:07 UTC by Ayush0730

…lso fixed a minor bug which was due to location of partials was incorrectly defined at one place

## What is the change?
Added a separate button to edit user profile on user dashboard and removed that button from navbar

## Related issue?
close: #639 

## How was it tested?
Tested locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![image](https://user-images.githubusercontent.com/68139755/114216059-03000d80-9984-11eb-9554-26c2653e435f.png)

2021-04-09 19:55 UTC, Pranav016 requested changes
Can you add a mobile view and tablet view screenshot ?
Coz you are using float class and it's usually not a good practice to use float to align items.

2021-04-10 10:08 UTC, Ayush0730 commented
> Can you add a mobile view and tablet view screenshot ?
> Coz you are using float class and it's usually not a good practice to use float to align items.

Tablet view : 
![image](https://user-images.githubusercontent.com/68139755/114266198-a8fa5900-9a12-11eb-968f-46d6bc5d17d3.png)

Mobile view:
![Uploading image.png…]()

Looks fine. Just one problem is there, username is moved slightly left side, due to which it does not remain centrally aligned

2021-04-10 10:26 UTC, Ayush0730 commented
Let me know, if this looks OK

![image](https://user-images.githubusercontent.com/68139755/114266701-45bdf600-9a15-11eb-9f7c-1840b8e0917e.png)

2021-04-10 10:28 UTC, Pranav016 commented
> Let me know, if this looks fine
> 
> ![image](https://user-images.githubusercontent.com/68139755/114266701-45bdf600-9a15-11eb-9f7c-1840b8e0917e.png)

Looks fine, some padding would help differentiate button from the text or having a different color for the button..

2021-04-10 10:30 UTC, Ayush0730 commented
Also there was a problem, like you can click anywhere on the row and it will be treated as click on link

![image](https://user-images.githubusercontent.com/68139755/114266761-99304400-9a15-11eb-89fc-dbaa2f1584e8.png)

Like in this screenshot, I have hovered over empty area on the same height as the name and edit btn

2021-04-10 10:31 UTC, Ayush0730 commented
> > Let me know, if this looks fine
> > ![image](https://user-images.githubusercontent.com/68139755/114266701-45bdf600-9a15-11eb-9f7c-1840b8e0917e.png)
> 
> Looks fine, some padding would help differentiate the button better from the text or having a different color for the button..

Okay, making a commit fixing this issue and 

> Also there was a problem, like you can click anywhere on the row and it will be treated as click on link
> 
> ![image](https://user-images.githubusercontent.com/68139755/114266761-99304400-9a15-11eb-89fc-dbaa2f1584e8.png)
> 
> Like in this screenshot, I have hovered over empty area on the same height as the name and edit btn

Okay making a commit fixing this issue and providing some padding on the button

2021-04-10 10:31 UTC, Pranav016 commented
> Also there was a problem, like you can click anywhere on the row and it will be treated as click on link
> 
> ![image](https://user-images.githubusercontent.com/68139755/114266761-99304400-9a15-11eb-89fc-dbaa2f1584e8.png)
> 
> Like in this screenshot, I have hovered over empty area on the same height as the name and edit btn

Probably some closing tag is missing, you can check. 
I'll review the code in an hour..

2021-04-10 10:39 UTC, Ayush0730 commented
![image](https://user-images.githubusercontent.com/68139755/114267026-2b851780-9a17-11eb-94ff-3f156235c740.png)

2021-04-10 12:13 UTC, Pranav016 approved these changes

2021-04-10 12:13 UTC, merged