Flagging comments feature issue#411
ALPHAVIO/BlogSite pull request #697
Opened 2021-04-16 16:49 UTC by Ayush0730

## What is the change?
Added a feature to add flags to comments and if flags are more than or equal to three, then comment will be deleted automatically. Once this PR get merged I will be making a PR to restrict deletion of comments to writer(of comment) only.
This feature can be improved more such that one person will be able to flag a comment only one time but that requires a different approach.

## Related issue?
close: #411 

## How was it tested?
Locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/68139755/115057551-d3ac4c00-9f01-11eb-82a2-c00c09500ca1.mp4

2021-04-16 17:32 UTC, Pranav016 requested changes
Maybe instead of a counter variable `flag=0`, you could use an array that stores the user name of the person flagging the comment. That way you can check from the array and prevent person from flagging again and use the length of the array as the number of times the comment got flagged. Let me know if this approach suites this usecase..

2021-04-16 17:32 UTC, Pranav016 commented on routes/post.router.js
> +        const isUser = !!req.user;
`!!` used here ?

2021-04-17 02:37 UTC, Ayush0730 commented
> Maybe instead of a counter variable `flag=0`, you could use an array that stores the user name of the person flagging the comment. That way you can check from the array and prevent person from flagging again and use the length of the array as the number of times the comment got flagged. Let me know if this approach suites this use case..

2021-04-17 06:59 UTC, Ayush0730 commented on routes/post.router.js
> +        const isUser = !!req.user;
It is for checking if user is Authenticated or not

2021-04-17 07:41 UTC, Ayush0730 commented
> Maybe instead of a counter variable `flag=0`, you could use an array that stores the user name of the person flagging the comment. That way you can check from the array and prevent person from flagging again and use the length of the array as the number of times the comment got flagged. Let me know if this approach suites this use case..

Done!!

2021-04-17 09:25 UTC, Pranav016 requested changes
changes look good, one thing. You checked the person has already flagged, now the flag button appears clicked or that individual ? I think for that you might have add this check in the post route as well other than the `/flag` route..

If you didn't get what I was trying to say then just add a demo video of the current changes and I'll explain..

2021-04-17 16:25 UTC, Ayush0730 commented
> changes look good, one thing. You checked the person has already flagged, now the flag button appears clicked or that individual ? I think for that you might have add this check in the post route as well other than the `/flag` route..
> 
> If you didn't get what I was trying to say then just add a demo video of the current changes and I'll explain..

For that, I would need to check for each comment in ejs file, post.ejs

2021-04-17 17:40 UTC, Ayush0730 commented
Please check if this is alright, there were many issues going on with my local branch. Please check for any mistakes, I may have made in committing and pushing

2021-04-17 17:47 UTC, Ayush0730 commented
Uploading bandicam 2021-04-17 23-16-32-669.mp4…

2021-04-17 17:48 UTC, Ayush0730 commented
https://user-images.githubusercontent.com/68139755/115121987-2efa3f00-9fd3-11eb-9a58-375f6c468ac7.mp4

Final feature demo video

2021-04-17 23:11 UTC, Pranav016 commented
>  bandicam.2021-04-17.23-16-32-669.mp4 
> Final feature demo video

Same person can't flag twice right ? So should we send some warning/error if the same person tries to flag again ?

2021-04-18 01:54 UTC, Ayush0730 commented
> > bandicam.2021-04-17.23-16-32-669.mp4
> > Final feature demo video
> 
> Same person can't flag twice right ? So should we send some warning/error if the same person tries to flag again ?

Well, flag button is disabled if the current user has already flagged that comment. So I don't think, this will ever happen

2021-04-18 14:26 UTC, merged