Added User profile feature
ALPHAVIO/BlogSite pull request #725
Opened 2021-04-21 09:09 UTC by Ayush0730

## What is the change?
Added User profile feature, profile image will be shown on user profile page and dashboard, also added feature to edit profile image

## Related issue?
close: #512 

## How was it tested?
Tested Locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/68139755/115528020-42e1c180-a2af-11eb-88f9-3a5f40cbfb71.mp4

2021-04-21 09:11 UTC, Ayush0730 commented
To clear any doubts, at 0:44, the profile picture shown is default for everyone, if they do not upload any profile picture at the time of signup. And users can see other users' profile picture

2021-04-21 09:22 UTC, Ayush0730 commented
Improved edit profile page

![image](https://user-images.githubusercontent.com/68139755/115530104-18910380-a2b1-11eb-91ba-e05fdb83cac7.png)

2021-04-21 19:49 UTC, Pranav016 requested changes
Looks good

2021-04-21 19:49 UTC, Pranav016 commented on views/useritems/dashboard.ejs
> +                <img src="<%= user.photo %>" class="img-thumbnail mx-auto" width="200px" alt="User Profile Image">
Don't add inline styling
replace `px` with one of these `rem em vh vw %` for responsiveness
add some border radius

2021-04-22 21:34 UTC, Pranav016 approved these changes

2021-04-22 21:35 UTC, Pranav016 commented
resolve conflicts **carefully**, after that I can merge

2021-04-22 21:35 UTC, Pranav016 commented
/gssoc/

2021-04-23 05:29 UTC, Ayush0730 commented
> resolve conflicts **carefully**, after that I can merge

Please check if it is Ok

2021-04-23 06:24 UTC, Pranav016 commented
> > resolve conflicts **carefully**, after that I can merge
> 
> Please check if it is Ok

The CI run and some changes were requested by the GitHub bot..

2021-04-23 06:30 UTC, Ayush0730 commented
> > > resolve conflicts **carefully**, after that I can merge
> > 
> > 
> > Please check if it is Ok
> 
> The last commit doesn't show anything so I am hoping the conflicts were resolved correctly otherwise we'll correct the bug later (if any), no problem.
> 
> Also, after resolving the conflicts the CI run and some changes were requested by the GitHub bot that need to be resolved
> Then I can merge.

How to solve that?

2021-04-23 06:32 UTC, Pranav016 commented
> > > > resolve conflicts **carefully**, after that I can merge
> > > 
> > > 
> > > Please check if it is Ok
> > 
> > 
> > The last commit doesn't show anything so I am hoping the conflicts were resolved correctly otherwise we'll correct the bug later (if any), no problem.
> > Also, after resolving the conflicts the CI run and some changes were requested by the GitHub bot that need to be resolved
> > Then I can merge.
> 
> How to solve that?

Run command `prettier --write .` locally.
Then run `npm run lint` to check if it is still giving any error..

2021-04-23 06:38 UTC, Ayush0730 commented
> > > > > resolve conflicts **carefully**, after that I can merge
> > > > 
> > > > 
> > > > Please check if it is Ok
> > > 
> > > 
> > > The last commit doesn't show anything so I am hoping the conflicts were resolved correctly otherwise we'll correct the bug later (if any), no problem.
> > > Also, after resolving the conflicts the CI run and some changes were requested by the GitHub bot that need to be resolved
> > > Then I can merge.
> > 
> > 
> > How to solve that?
> 
> Run command `prettier --write .` locally.
> Then run `npm run lint` to check if it is still giving any error..

![image](https://user-images.githubusercontent.com/68139755/115829336-8150bb00-a42c-11eb-8d63-ecffc9ccb6d9.png)
😥

2021-04-23 06:40 UTC, Ayush0730 commented
after running npm run lint command it has done many file changes

should i push the changes?

2021-04-23 06:43 UTC, Pranav016 commented
> after running npm run lint command it has done many file changes
> 
> should i push the changes?

Also do `npm run lint-check` to check if all errors are gone

2021-04-23 06:44 UTC, Pranav016 commented
> > > > > > resolve conflicts **carefully**, after that I can merge
> > > > > 
> > > > > 
> > > > > Please check if it is Ok
> > > > 
> > > > 
> > > > The last commit doesn't show anything so I am hoping the conflicts were resolved correctly otherwise we'll correct the bug later (if any), no problem.
> > > > Also, after resolving the conflicts the CI run and some changes were requested by the GitHub bot that need to be resolved
> > > > Then I can merge.
> > > 
> > > 
> > > How to solve that?
> > 
> > 
> > Run command `prettier --write .` locally.
> > Then run `npm run lint` to check if it is still giving any error..
> 
> ![image](https://user-images.githubusercontent.com/68139755/115829336-8150bb00-a42c-11eb-8d63-ecffc9ccb6d9.png)
> 😥

Do you have up to date project? Because a lot of these errors I solved a couple days ago

2021-04-23 06:44 UTC, Pranav016 commented
> after running npm run lint command it has done many file changes
> 
> should i push the changes?

Yes you can push it

2021-04-23 06:52 UTC, Ayush0730 commented
> > after running npm run lint command it has done many file changes
> > should i push the changes?
> 
> Yes you can push it

Its all messed up

2021-04-23 07:01 UTC, Pranav016 commented
> Its all messed up

still showing errors in the CI, I'll check

2021-04-23 07:06 UTC, Pranav016 commented
> > Its all messed up
> 
> still showing errors in the CI, I'll check

on my machine it's not showing any linting errors.
`npm run lint` should solve the errors, idk whats the issue here

2021-04-23 07:09 UTC, Ayush0730 commented
> > > Its all messed up
> > 
> > 
> > still showing errors in the CI, I'll check
> 
> on my machine it's not showing any linting errors.
> `npm run lint` should solve the errors, idk whats the issue here

What should I do now?

2021-04-23 07:12 UTC, merged

2021-04-23 07:13 UTC, Pranav016 commented
/level2/